###
POST http://localhost:3000/auth/register
content-type: application/json

{
    "email": "test123@gmail.com",
    "password": "test123",
    "username": "test123",
    "name": "test123"
}


###
POST http://localhost:3000/auth/login
content-type: application/json

{
    "email": "test1234@gmail.com",
    "password": "test1234"
}