###
GET http://localhost:8000/posts/
content-type: application/json


###
POST http://localhost:8000/posts/
content-type: application/json

{
    "user": "65807eee6037cf53effee617", 
    "title": "post check",
    "imagePath": "/image/path",
    "likes": 10,
    "content": "This is a post check content"
}

###
GET http://localhost:8000/posts/32532523
content-type: application/json

###
DELETE  http://localhost:8000/posts/658bd86436ccfbb51b848e08
content-type: application/json

### - Invalid post id
DELETE  http://localhost:8000/posts/dofsdk23134
content-type: application/json

###
PUT   http://localhost:8000/posts/658bdd094d95c7557458f562
content-type: application/json

{
    "user": "65807eee6037cf53effee617", 
    "title": "post updated",
    "imagePath": "/image/path/updated",
    "likes": 10,
    "content": "This post updated 2"
}
