###
GET http://localhost:8000/posts/
content-type: application/json


###
POST http://localhost:8000/posts/
content-type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzSW4iOiIxMmgiLCJpZCI6IjY1OTFlZjUyMjcwN2QxOWIyYzBiYjk3ZSIsInByb3ZpZGVyIjoiZW1haWwiLCJlbWFpbCI6InRlc3QxMjNAZ21haWwuY29tIiwiaWF0IjoxNzA0MDY2NDg5fQ.8nW7NG-tGSy0IFRIjYdc1P0N2o3e90M86xqjOKLVMdc

{
    "title": "post title test no image",
    "content": "post content test no image"
}

### Invalid post schema - no user, no title
POST http://localhost:8000/posts/
content-type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzSW4iOiIxMmgiLCJpZCI6IjY1OTFlZjUyMjcwN2QxOWIyYzBiYjk3ZSIsInByb3ZpZGVyIjoiZW1haWwiLCJlbWFpbCI6InRlc3QxMjNAZ21haWwuY29tIiwiaWF0IjoxNzA0MDYyODA0fQ.XzjeNlIMUMdh-9s76m_ytaszgjtRtVMo5vzGDPJe3j8

{
    "imagePath": "/image/path",
    "likes": [],
    "content": "This is a post check content"
}

###
GET http://localhost:8000/posts/32532523
content-type: application/json

###
DELETE  http://localhost:8000/posts/658bdd094d95c7557458f562
content-type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzSW4iOiIxMmgiLCJpZCI6IjY1OTFlZjUyMjcwN2QxOWIyYzBiYjk3ZSIsInByb3ZpZGVyIjoiZW1haWwiLCJlbWFpbCI6InRlc3QxMjNAZ21haWwuY29tIiwiaWF0IjoxNzA0MDYyODA0fQ.XzjeNlIMUMdh-9s76m_ytaszgjtRtVMo5vzGDPJe3j8

### - Invalid post id
DELETE  http://localhost:8000/posts/658bdd094d95c7557458f562
content-type: application/json

###
PUT   http://localhost:8000/posts/658ec5417fc82b6f7949a43c
content-type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzSW4iOiIxMmgiLCJpZCI6IjY1OTFlZjUyMjcwN2QxOWIyYzBiYjk3ZSIsInByb3ZpZGVyIjoiZW1haWwiLCJlbWFpbCI6InRlc3QxMjNAZ21haWwuY29tIiwiaWF0IjoxNzA0MDYyODA0fQ.XzjeNlIMUMdh-9s76m_ytaszgjtRtVMo5vzGDPJe3j8

{
    "user": "65807eee6037cf53effee617", 
    "title": "post updated @@@",
    "imagePath": "/image/path/updated",
    "likes": ["updated", "updated2"],
    "content": "This post updated 2"
}

###
PATCH   http://localhost:8000/posts/658ec5417fc82b6f7949a43c
content-type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzSW4iOiIxMmgiLCJpZCI6IjY1OTFlZjUyMjcwN2QxOWIyYzBiYjk3ZSIsInByb3ZpZGVyIjoiZW1haWwiLCJlbWFpbCI6InRlc3QxMjNAZ21haWwuY29tIiwiaWF0IjoxNzA0MDYyODA0fQ.XzjeNlIMUMdh-9s76m_ytaszgjtRtVMo5vzGDPJe3j8

{
    "likes": ["updated-versio3-2", "updated-versio3-3"]
}

